"""Deterministic Mock TTS Provider — Phase 2 / M2.
Generates REAL valid audio using FFmpeg (sine tone + optional text representation via metadata).
Not a fake metadata-only provider.
Clearly marked as synthetic/development audio.
"""
from __future__ import annotations
import subprocess
import hashlib
from pathlib import Path
from autopilot.providers.contracts import TTSProvider, ProviderHealth, CapabilityMetadata, CostUsageMetadata, ProviderErrorType
from autopilot.core.config import CONFIG


class MockTTSProvider(TTSProvider):
    provider_name = "mock_tts"
    capability = CapabilityMetadata(
        max_resolution="1080p", supports_9_16=True, local_only=True,
        license_note="Deterministic mock TTS using FFmpeg; synthetic audio only",
    )
    error_type = ProviderErrorType.UNCONFIGURED
    cost_meta = CostUsageMetadata(estimated_usd=0.0, provider_type="local")

    def health_check(self) -> ProviderHealth:
        try:
            r = subprocess.run(["ffmpeg", "-version"], capture_output=True, timeout=5)
            return ProviderHealth(healthy=True, provider_name=self.provider_name, details={"ffmpeg_available": r.returncode == 0, "mode": "synthetic"})
        except Exception as exc:
            return ProviderHealth(healthy=False, provider_name=self.provider_name, error=str(exc))

    def synthesize(self, text: str, out_path: str, voice_id: str | None = None, **kwargs) -> str:
        out = Path(out_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        # Deterministic synthetic audio: sine tone at 1000Hz, duration based on word count / configurable WPM
        word_count = len(text.split()) if text else 1
        duration_sec = max(1.0, word_count / 150.0 * 60.0)
        # Use FFmpeg to generate real WAV
        cmd = [
            "ffmpeg", "-y",
            "-f", "lavfi",
            "-i", f"sine=frequency=1000:duration={duration_sec}",
            "-ac", "1",
            "-ar", "22050",
            "-c:a", "pcm_s16le",
            str(out),
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError(f"Mock TTS FFmpeg failed: {result.stderr}")
        # Write provenance sidecar
        prov_path = out.with_suffix(out.suffix + ".provenance.json")
        import json
        prov_path.write_text(json.dumps({
            "provider": self.provider_name,
            "input_text_hash_prefix": hashlib.sha256(text.encode()).hexdigest()[:16],
            "voice_id": voice_id or "default",
            "duration_estimated_sec": round(duration_sec, 2),
            "mode": "synthetic",
            "note": "Deterministic test audio generated by MockTTSProvider",
        }), encoding="utf-8")
        return str(out)
